[2024-09-19T23:33:23.623+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.raw_ingestion manual__2024-09-19T23:33:22.802158+00:00 [queued]>
[2024-09-19T23:33:23.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.raw_ingestion manual__2024-09-19T23:33:22.802158+00:00 [queued]>
[2024-09-19T23:33:23.633+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-19T23:33:23.652+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): raw_ingestion> on 2024-09-19 23:33:22.802158+00:00
[2024-09-19T23:33:23.657+0000] {standard_task_runner.py:57} INFO - Started process 2390 to run task
[2024-09-19T23:33:23.660+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'raw_ingestion', 'manual__2024-09-19T23:33:22.802158+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmpgerpbbgp']
[2024-09-19T23:33:23.661+0000] {standard_task_runner.py:85} INFO - Job 219: Subtask raw_ingestion
[2024-09-19T23:33:23.765+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.raw_ingestion manual__2024-09-19T23:33:22.802158+00:00 [running]> on host airflow-worker
[2024-09-19T23:33:23.953+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='raw_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T23:33:22.802158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T23:33:22.802158+00:00'
[2024-09-19T23:33:23.955+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-19T23:33:23.956+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-19T23:33:23.985+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-19T23:33:23.986+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-19T23:33:23.996+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-19T23:33:24.077+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-09-19T23:33:24.078+0000] {ssh.py:478} INFO - Running command: export SPARK_HOME=/usr/local/spark; /opt/conda/bin/spark-submit --master local[*] --executor-memory 2g /opt/shared/scripts/raw_ingestion.py 2024-09-19
[2024-09-19T23:33:26.314+0000] {ssh.py:524} INFO - Traceback (most recent call last):
[2024-09-19T23:33:26.314+0000] {ssh.py:524} INFO -   File "/opt/shared/scripts/raw_ingestion.py", line 8, in <module>
[2024-09-19T23:33:26.316+0000] {ssh.py:524} INFO -     n = int(sys.argv[1])
[2024-09-19T23:33:26.316+0000] {ssh.py:524} INFO - ValueError: invalid literal for int() with base 10: '2024-09-19'
[2024-09-19T23:33:26.348+0000] {ssh.py:524} INFO - 24/09/19 23:33:26 INFO ShutdownHookManager: Shutdown hook called
[2024-09-19T23:33:26.350+0000] {ssh.py:524} INFO - 24/09/19 23:33:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-9136d2da-73af-47a5-9fd4-181d12f53fff
[2024-09-19T23:33:26.447+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 166, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 160, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-09-19T23:33:26.449+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=raw_ingestion, task_id=raw_ingestion, execution_date=20240919T233322, start_date=20240919T233323, end_date=20240919T233326
[2024-09-19T23:33:26.468+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 219 for task raw_ingestion (SSH operator error: exit status = 1; 2390)
[2024-09-19T23:33:26.480+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-19T23:33:26.518+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
