[2024-09-15T20:02:23.657+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.raw_ingestion scheduled__2024-09-13T01:00:00+00:00 [queued]>
[2024-09-15T20:02:23.665+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.raw_ingestion scheduled__2024-09-13T01:00:00+00:00 [queued]>
[2024-09-15T20:02:23.666+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 11
[2024-09-15T20:02:23.680+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): raw_ingestion> on 2024-09-13 01:00:00+00:00
[2024-09-15T20:02:23.684+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2024-09-15T20:02:23.688+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'raw_ingestion', 'scheduled__2024-09-13T01:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmpov23nlfu']
[2024-09-15T20:02:23.689+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask raw_ingestion
[2024-09-15T20:02:23.810+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.raw_ingestion scheduled__2024-09-13T01:00:00+00:00 [running]> on host airflow-worker
[2024-09-15T20:02:24.028+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='raw_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T01:00:00+00:00'
[2024-09-15T20:02:24.029+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-15T20:02:24.029+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-15T20:02:24.061+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-15T20:02:24.062+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-15T20:02:24.071+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-15T20:02:24.162+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-09-15T20:02:24.163+0000] {ssh.py:478} INFO - Running command: export SPARK_HOME=/usr/local/spark; /opt/conda/bin/spark-submit --master local[*] --executor-memory 2g /opt/shared/scripts/raw_ingestion.py
[2024-09-15T20:02:26.219+0000] {ssh.py:524} INFO - Traceback (most recent call last):
[2024-09-15T20:02:26.219+0000] {ssh.py:524} INFO -   File "/opt/shared/scripts/raw_ingestion.py", line 1, in <module>
[2024-09-15T20:02:26.221+0000] {ssh.py:524} INFO -     import requests
[2024-09-15T20:02:26.221+0000] {ssh.py:524} INFO - ModuleNotFoundError: No module named 'requests'
[2024-09-15T20:02:26.230+0000] {ssh.py:524} INFO - 24/09/15 20:02:26 INFO ShutdownHookManager: Shutdown hook called
[2024-09-15T20:02:26.232+0000] {ssh.py:524} INFO - 24/09/15 20:02:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-74b7da0e-5d6e-497b-8cc4-c6057680e9c6
[2024-09-15T20:02:26.343+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 166, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 160, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-09-15T20:02:26.346+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_ingestion, task_id=raw_ingestion, execution_date=20240913T010000, start_date=20240915T200223, end_date=20240915T200226
[2024-09-15T20:02:26.379+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task raw_ingestion (SSH operator error: exit status = 1; 63)
[2024-09-15T20:02:26.428+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-15T20:02:26.469+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
